name: stacked_app2
description: Stacked App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  sqflite: ^2.4.2
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  
  o_package:
    path: "module/o_package"
  equatable: ^2.0.7

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

